CREATE TABLE PERFIL(
	ID BIGINT AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(254) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE MATERIA(
	ID BIGINT AUTO_INCREMENT NOT NULL,
	NOME VARCHAR(254) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE CURSO (
	ID BIGINT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(254) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE CURSO_MATERIA (
	ID_CURSO BIGINT NOT NULL,
    ID_MATERIA BIGINT NOT NULL,
    PRIMARY KEY (ID_CURSO, ID_MATERIA),
    FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID),
    FOREIGN KEY (ID_MATERIA) REFERENCES MATERIA(ID)
);
CREATE TABLE ENDERECO (
ID  BIGINT  NOT NULL AUTO_INCREMENT,
RUA VARCHAR (200) NOT NULL,
CEP VARCHAR(8) NOT NULL,
BAIRRO VARCHAR(100) NOT NULL,
CIDADE VARCHAR (100) NOT NULL,
ESTADO VARCHAR(100) NOT NULL,
COMPLEMENTO VARCHAR(200),
NUMERO MEDIUMINT NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE USUARIO (
ID BIGINT  NOT NULL AUTO_INCREMENT,
NOME VARCHAR(254),
ID_PERFIL BIGINT NOT NULL,
ID_ENDERECO BIGINT NOT NULL,
FOREIGN KEY(ID_PERFIL) REFERENCES PERFIL(ID),
FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO(ID),
EMAIL VARCHAR (254),
SENHA VARCHAR(8),
DATA_NASCIMENTO DATE,
PRIMARY KEY(ID)
);

CREATE TABLE USUARIO_CURSO (
ID_ALUNO BIGINT NOT NULL,
ID_CURSO BIGINT NOT NULL,
FOREIGN KEY (ID_ALUNO) REFERENCES USUARIO(ID),
FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID),
PRIMARY KEY(ID_ALUNO, ID_CURSO)

);


CREATE TABLE USUARIO_MATERIA (
ID_PROFESSOR BIGINT NOT NULL,
ID_MATERIA BIGINT NOT NULL,
FOREIGN KEY (ID_PROFESSOR) REFERENCES USUARIO(ID),
FOREIGN KEY (ID_MATERIA) REFERENCES MATERIA(ID),
PRIMARY KEY(ID_PROFESSOR, ID_MATERIA)

);



CREATE TABLE AVALIACAO (
ID BIGINT AUTO_INCREMENT NOT NULL,
VALOR_AVALIACAO DOUBLE,
PERIODO VARCHAR(30),
ID_MATERIA BIGINT NOT NULL,
ID_ALUNO BIGINT NOT NULL,
ID_PROFESSOR BIGINT NOT NULL,
FOREIGN KEY (ID_MATERIA) REFERENCES MATERIA(ID),
FOREIGN KEY (ID_ALUNO) REFERENCES USUARIO(ID),
FOREIGN KEY (ID_PROFESSOR) REFERENCES USUARIO(ID),
 PRIMARY KEY(ID)
);









